version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    networks:
      - counter-net
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: True
  redis:
    image: "redis:alpine"
    volumes:
      - redis:/data
    networks:
      counter-net:

networks:
  counter-net:

volumes:
  redis: